[package]
name        = "eoh-lsp"
description = "Eye of Horus — Language Server Protocol implementation"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
repository.workspace = true

[dependencies]
eoh-core     = { path = "../eoh-core" }
eoh-lexer    = { path = "../eoh-lexer" }
eoh-parser   = { path = "../eoh-parser" }
eoh-compiler = { path = "../eoh-compiler" }
thiserror    = { workspace = true }
serde        = { workspace = true }
serde_json   = { workspace = true }
tokio        = { workspace = true }
log          = { workspace = true }
